name: "Release"

on:
  push:
    tags:
      - "v*.*.*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Artifacts:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: GitHub Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
          cache: true

      - name: Build steam tools
        run: |
         ./build.sh ge ./build/GE-Proton-Fusion
         ./build.sh tkg-valvebe ./build/Proton-Tkg-Valvebe-Fusion
         ./build.sh tkg-wine ./build/Proton-Tkg-Wine-Fusion
         tar -czf ./build/GE-Proton-Fusion.tar.gz -C ./build/GE-Proton-Fusion .
         tar -czf ./build/Proton-Tkg-Valvebe-Fusion.tar.gz -C ./build/Proton-Tkg-Valvebe-Fusin .
         tar -czf ./build/Proton-Tkg-Wine-Fusion.tar.gz -C ./build/Proton-Tkg-Wine-Fusion .

      - name: Release on GitHub
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          fail_on_unmatched_files: true
          files: |
            ./build/GE-Proton-Fusion.tar.gz
            ./build/Proton-Tkg-Valvebe-Fusion.tar.gz
            ./build/Proton-Tkg-Wine-Fusion.tar.gz
