name: "Test"

on:
  push:
    branches: ["main"]
    paths:
      - "**.rs"
      - "Cargo.toml"
      - "Cargo.lock"
  pull_request:
    branches: ["main"]
    paths:
      - "**.rs"
      - "Cargo.toml"
      - "Cargo.lock"
    types: [ready_for_review, opened, synchronize]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Proton-Updater:
    name: proton-updater
    if: github.event.pull_request.draft == false || github.event_name == 'push'
    runs-on: ubuntu-22.04
    steps:
      - name: GitHub Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
          cache: true

      - name: Ensure code compiles
        working-directory: ./proton-updater
        run: |
          cargo build --all
          cargo build --all --release

      - name: Run Tests
        working-directory: ./proton-updater
        run: cargo test --all

      - name: Run Clippy
        working-directory: ./proton-updater
        run: cargo clippy --all -- -D warnings

      - name: Run Rustfmt
        working-directory: ./proton-updater
        run: cargo fmt --all --check
